// File generated by FlutterFire CLI.
// ignore_for_file: lines_longer_than_80_chars, avoid_classes_with_only_static_members
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for macos - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyAo5SBtfRTuo-On9_AnGGsddHwD5iGvLuQ',
    appId: '1:655009320556:web:b65f066ee7f2f031805249',
    messagingSenderId: '655009320556',
    projectId: 'quadballmanager',
    authDomain: 'quadballmanager.firebaseapp.com',
    storageBucket: 'quadballmanager.appspot.com',
    measurementId: 'G-VP8GH2N5LL',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyAzpB-mMPEKAI7iF86yIlJJqFLmR5nDiRs',
    appId: '1:655009320556:android:42337a2e199f8a82805249',
    messagingSenderId: '655009320556',
    projectId: 'quadballmanager',
    storageBucket: 'quadballmanager.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyABAf2PYbK6D0xSzLYuyGNCiGNu1M3I8WY',
    appId: '1:655009320556:ios:0c1ffcaed14548ce805249',
    messagingSenderId: '655009320556',
    projectId: 'quadballmanager',
    storageBucket: 'quadballmanager.appspot.com',
    iosBundleId: 'com.example.quadballManager',
  );
}
